In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.7.1+cpu


In [3]:
# Scalar
scalar = torch.tensor(7)
# return tensor back as integer
scalar.item()
# Vector
vector = torch.tensor([7, 7])
print(vector.ndim)
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
print(MATRIX.ndim)
print(MATRIX.shape)

1
2
torch.Size([2, 2])


In [4]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6], 
                        [7, 8, 9]]])
print(TENSOR.shape)
print(TENSOR.ndim)
SECOND_TENSOR = torch.tensor([[[1, 2, 3, 28],
                               [4, 5, 6, 27], 
                               [7, 8, 9, 22],
                               [30, 31, 32, 33]],
                               [[10, 11, 12, 21],
                               [13, 14, 15, 19], 
                               [16, 17, 18, 20],
                               [34, 35, 36, 37]]])
print(SECOND_TENSOR.shape)

print(SECOND_TENSOR.ndim)

torch.Size([1, 3, 3])
3
torch.Size([2, 4, 4])
3


### Random Tensors


In [5]:
# Random tensor of size (3, 4)

random_tensor = torch.rand(1, 6, 7)

# Random tensor with a similar shape to an image tensor

image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)
image_size_tensor.shape, image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones


In [ ]:
zeros = torch.zeros(6, 7)
ones = torch.ones(6, 7)

tensor([[[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]]])

### Create a range of tensors and tensors-like

In [ ]:
one_to_ten = torch.arange(start=1, end=100, step=10)
ten_zeros = torch.zeros_like(input=one_to_ten)

ten_zeros, one_to_ten

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]))

### Tensor datatypes

3 of the biggest errors when using tensors:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device


In [ ]:
float_32_tensor = torch.tensor([3.3, 6.6, 9.9], dtype=None, # What datatype is the tensor?
                                                device=None, # What device is your tensor on?
                                                requires_grad=False) # Whether or not to track gradients for the tensor
 
float_16_tensor = float_32_tensor.type(torch.float16) # Change the datatype of a tensor to float16


### Getting information from tensors (tensor attributes)

1. Datatype -  `tensor.dtype`
2. Shape -  `tensor.shape`
3. Device -  `tensor.device`


In [24]:
random_tensor = torch.rand(3, 4, dtype=torch.float16)
print(random_tensor)
print(f"Datatype: {random_tensor.dtype}") # Get the datatype of a tensor
print(f"Shape: {random_tensor.shape}") # Get the shape of a tensor
print(f"Device: {random_tensor.device}") # Get the device of a tensor

tensor([[0.0552, 0.8706, 0.7588, 0.8379],
        [0.0327, 0.2466, 0.3848, 0.2026],
        [0.7769, 0.1196, 0.7993, 0.3477]], dtype=torch.float16)
Datatype: torch.float16
Shape: torch.Size([3, 4])
Device: cpu


### Tensor operations

Tensors operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [32]:
first_tensor = torch.tensor([1, 2, 3])

# Add 10 to every element in the first_tensor
first_tensor = first_tensor + 10

# Multiply every element in the first_tensor by 10
first_tensor = first_tensor * 10

# Subtract 10 from every element in the first_tensor
first_tensor = first_tensor - 10

# Use PyToch's built-in functions
torch.mul(first_tensor, 10)

torch.add(first_tensor, 10)





tensor([110, 120, 130])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication

In [33]:
# Element-wise multiplication
tensor = torch.tensor([1, 2, 3])
print(tensor * tensor)

tensor([1, 4, 9])


In [ ]:
# Matrix multiplication

torch.matmul(tensor, tensor) # Product of 1 * 1 + 2 * 2 + 3 * 3

tensor(14)